# This file was generated by GoReleaser. DO NOT EDIT.
class Proaction < Formula
  desc "Build better GitHub Action Workflows"
  homepage "https://proaction.io"
  version "0.4.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/proactionhq/proaction/releases/download/v0.4.2/proaction_darwin_amd64.tar.gz"
    sha256 "867099c33bdc70fab3621c75ecd95c07130ec86679ea15d796857d8d07efde1b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/proactionhq/proaction/releases/download/v0.4.2/proaction_linux_amd64.tar.gz"
      sha256 "23adc393fa422fa2a06c31305a757d097877f50f708f4642787d3f75cafb6d9a"
    end
  end

  def install
    bin.install "proaction"
  end
end
