# This file was generated by GoReleaser. DO NOT EDIT.
class Proaction < Formula
  desc "Build better GitHub Action Workflows"
  homepage "https://proaction.io"
  version "0.3.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/proactionhq/proaction/releases/download/v0.3.1/proaction_darwin_amd64.tar.gz"
    sha256 "a42552a52373780b79a6ef8b7ea85c0d8f34b54563b937355890f788511d7a41"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/proactionhq/proaction/releases/download/v0.3.1/proaction_linux_amd64.tar.gz"
      sha256 "66cccad46fd3f0df1c490f718435f5e6082fae17d79fa6bdbb9aed2ecff234dc"
    end
  end

  def install
    bin.install "proaction"
  end
end
